dirs:
  ds_one:
    when_modified:
      file_patterns:
      - ds_one/*.tf
      - modules/shared/*.tf
  ds_two:
    when_modified:
      file_patterns:
      - ds_two/*.tf
      - modules/shared/*.tf
  modules/**:
    when_modified:
      file_patterns: []
engine:
  name: tofu
